# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64f8f87c5c03cbf82fa158bc8e66159f5314076400e5bd54a2843dedc84ce625088562666b337c11a509d6eb16437ff5d27c8311d9a15ec4e3ab395d5f23553c

test:
  secret_key_base: 49e193a5673cc0d39d1c8e80ffdd282e798945c570f893c1dc4d03fcc7feb2bbf5696b2d520cca734b6e13befd4eb436f68057056aa38f9fd9bada1111768aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
